markdown: kramdown

kramdown:
  input: GFM
  highlighter: rouge

title: genkami.github.io

twitter:
  user: cloudear8

google_analytics: UA-100936400-1

lang: ja

gems:
  - jekyll-sitemap
  - jemoji

# rss
name: genkami.github.io
description: blog
url: https://genkami.github.io/