markdown: kramdown

kramdown:
  input: GFM
  highlighter: rouge

title: ゴバブログ

twitter:
  user: cloudear8

google_analytics: UA-100936400-1

lang: ja
encoding: UTF-8

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

# rss
name: ゴバブログ
description: プログラミング関係のメモ等
url: https://genkami.github.io

num_recent_posts: 10
num_articles_per_page: 10
num_related_posts: 5

exclude:
  - vendor
