markdown: kramdown

kramdown:
  input: GFM
  highlighter: rouge

title: genkami.github.io

twitter:
  user: cloudear8

google_analytics: UA-100936400-1

lang: ja
encoding: UTF-8

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

# rss
name: genkami.github.io
description: blog
url: https://genkami.github.io/

num_recent_posts: 10
num_articles_per_page: 10